name: Renovate Dependencies

on:
  workflow_dispatch:


jobs:
  renovate-dependencies:
    name: Renovate Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run renovate bot
        uses: renovatebot/github-action@v27.19.3
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
